gitea:
  ingress:
    enabled: true
   #className: nginx
    hosts:
      - host: &host git.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host
  gitea:
    admin:
      username: devops
      password: devops
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: http://gitea-http.gitea:3000
      webhook:
        ALLOWED_HOST_LIST: private
#  global:
#    storageClass: local-path
  persistence:
    storageClass: local-path
  postgresql:
    persistence:
      enabled: true
      storageClass: local-path
